### ISSUE TITLE
Activate oauth2 automatically when needed

### ISSUE THREAD

**Issue by fantapsody** [streamnative/pulsarctl#1073]
If `pulsarctl` is configured to use `oauth2` for authentication, it needs to run `pulsarctl oauth2 activate` first before any pulsar commands. Is it possible to activate oauth2 automatically when needed like `pulsar-admin` which doesn't need this additional step?

**Comment by EronWright** [comment]
Frankly it looks to me that some functionality is regressing here, specifically the ability to use `pulsarctl` with a user account rather than a service account.  See my comment [here](https://streamnative.slack.com/archives/C02LDG5V0LW/p1685639548274269?thread_ts=1685011904.670459&cid=C02LDG5V0LW).
