### ISSUE TITLE
Add pulsarctl to homebrew

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsarctl#118]
*Motivation*

Currently users have to download `pulsarctl` from github releases. It would be great if MacOS users can just install pulsarctl via `brew install pulsarctl`

**Comment by EronWright** [comment]
One idea to consider is to add `pulsar` rather than `pulsarctl` to brew.   The former would assumedly include the latter, but also make it easy to start Pulsar standalone, possibly as a [brew service](https://github.com/Homebrew/homebrew-services) (i.e. a Mac launchd service).

There's an example of this at [streamlio/homebrew-formulae](https://github.com/streamlio/homebrew-formulae), which installs Pulsar as a brew service:
```
$ brew services list
Name    Status  User Plist
pulsar  started eron /Users/eron/Library/LaunchAgents/homebrew.mxcl.pulsar.plist

$ brew services start pulsar
==> Successfully started `pulsar` (label: homebrew.mxcl.pulsar)

$ pulsarctl tenants list
+-------------+
| TENANT NAME |
+-------------+
| public      |
| sample      |
+-------------+
```

**Comment by sijie** [comment]
We can add two entries in the formulae. one for pulsar service and one for pulsarctl. because sometimes people want to just install `pulsarctl`.
